name: Node App CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # ------------------------------
    # CHECKOUT CODE
    # ------------------------------
    - name: Checkout Code
      uses: actions/checkout@v4

    # ------------------------------
    # NODE SETUP + INSTALL DEPENDENCIES
    # ------------------------------
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install Dependencies
      run: |
        echo "Node version:"
        node -v
        echo "NPM version:"
        npm -v
        npm install --no-audit --no-fund

    # ------------------------------
    # SONARQUBE ANALYSIS
    # ------------------------------
    - name: SonarQube Scan
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        echo "Running SonarQube analysis..."
        /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=nodeapp \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

    # ------------------------------
    # UPLOAD TAR TO NEXUS
    # ------------------------------
    - name: Upload Artifact to Nexus
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
      run: |
        echo "Creating TAR..."
        tar --ignore-failed-read --warning=no-file-changed \
            -czf nodeapp.tar.gz *

        echo "Uploading to Nexus..."
        curl -v -u $NEXUS_USER:$NEXUS_PASS \
          --upload-file nodeapp.tar.gz \
          http://3.89.29.36:8081/repository/nodejs/nodeapp.tar.gz

    # ------------------------------
    # BUILD DOCKER IMAGE
    # ------------------------------
    - name: Build Docker Image
      run: |
        echo "Building Docker image..."
        docker build -t kishangollamudi/nodeapp:latest .

    # ------------------------------
    # PUSH DOCKER IMAGE TO DOCKERHUB
    # ------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Push Docker Image
      run: |
        docker push kishangollamudi/nodeapp:latest
